name: Build and deploy Python app to Azure Web App - grpitiq-backend

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Change to backend folder
      run: cd backend

    - name: Install dependencies
      run: |
        cd backend
        python -m venv antenv
        source antenv/bin/activate
        pip install -r requirements.txt

    - name: Upload artifact for deployment
      uses: actions/upload-artifact@v4
      with:
        name: python-app
        path: backend

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: grpitiq-backend
        slot-name: production
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
        package: backend
